# Generated by Django 5.0.1 on 2024-02-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageimage',
            name='image',
            field=models.ImageField(upload_to='static/img/package_images/'),
        ),
    ]
