# Generated by Django 5.0.2 on 2024-02-22 01:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
