# Generated by Django 5.0.1 on 2024-02-26 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Package',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='management.package'),
        ),
    ]
