# Generated by Django 5.0.1 on 2024-03-25 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
    ]
